#!/usr/bin/env python3
"""Generate embedded fonts for the SPIDriver firmware C port.

Two fonts, matching the original firmware:

* ``micro`` -- 4x5 hexadecimal glyphs, extracted from the original
  ``firmware/st7735s/hex4x5.png``. 16 glyphs, nibble packed (2 px/byte).

* ``big``   -- the main display font.  The original used IBM Plex Sans
  SemiBold at 13 pt; we regenerate the same face at ~13 px, 4-bit
  grayscale, nibble packed.

Usage:
    python3 tools/genfonts.py > src/fonts.h
"""

import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PNG = "/devel/src/spidriver/firmware/st7735s/hex4x5.png"
FONT = os.path.expanduser("~/.local/share/fonts/IBMPlexSans-SemiBold.otf")
# Unique characters rendered by the original mkfont.py tplan
BIG_CHARS = "".join(sorted(set("SCKMISOAB0123456789.mAV")))


def pack_nibbles(pixels):
    """Pack 0..15 values into bytes, 2 per byte, zero-padded to even length."""
    out = []
    if len(pixels) % 2:
        pixels = pixels + [0]
    for i in range(0, len(pixels), 2):
        out.append((pixels[i] << 4) | pixels[i + 1])
    return out


def fmt_bytes(data, indent="        "):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append(indent + ", ".join("0x%02x" % b for b in chunk) + ",")
    return "\n".join(lines)


def gen_micro():
    im = Image.open(PNG).convert("L")
    glyphs = []
    for i in range(16):
        crop = im.crop((5 * i, 0, 5 * i + 4, 5))
        px = [int(v) // 16 for v in crop.getdata()]  # type: ignore[operator]  # 0..255 -> 0..15
        glyphs.append(pack_nibbles(px))  # 20 px -> 10 bytes
    return glyphs


def gen_big():
    font = ImageFont.truetype(FONT, 13)
    glyphs = []
    for ch in BIG_CHARS:
        im = Image.new("L", (24, 20))
        dr = ImageDraw.Draw(im)
        dr.text((2, 0), ch, font=font, fill=255)
        bbox = im.getbbox()
        if bbox is None:
            bbox = (2, 0, 4, 6)
        x1, y1 = bbox[2], bbox[3]
        if ch in "0123456789":
            # digits are fixed 8x9 like the original mkfont.py
            crop = im.crop((2, 0, 10, 9))
        else:
            # top-anchored at y=0, left at x=2, width/height from tight bbox
            crop = im.crop((2, 0, x1, y1))
        cw, chh = crop.size
        px = [(int(v) * 15) // 255 for v in crop.getdata()]  # type: ignore[operator]  # 0..255 -> 0..15
        glyphs.append((ch, cw, chh, pack_nibbles(px)))
    return glyphs


def emit_big(glyphs):
    print("typedef struct {")
    print("    char ch;")
    print("    uint8_t w;")
    print("    uint8_t h;")
    print("    const uint8_t *bits;  /* (w*h+1)/2 bytes, nibble packed */")
    print("} big_glyph_t;")
    print()
    for ch, w, h, bits in glyphs:
        name = "big_0x%02x" % ord(ch)
        print("static const uint8_t %s[] = {" % name)
        print(fmt_bytes(bits))
        print("};")
    print()
    print("static const big_glyph_t big_font[] = {")
    for ch, w, h, bits in glyphs:
        print("    { '%s', %d, %d, big_0x%02x }," % (ch, w, h, ord(ch)))
    print("};")
    print("#define BIG_FONT_COUNT %d" % len(glyphs))


def main():
    micro = gen_micro()
    big = gen_big()

    print("/* Generated by tools/genfonts.py -- do not edit. */")
    print("#ifndef SPIDRIVER_FONTS_H")
    print("#define SPIDRIVER_FONTS_H")
    print("#include <stdint.h>")
    print()

    print("/* 4x5 hexadecimal glyphs (from hex4x5.png), 2 px/byte, index 0..15 */")
    print("static const uint8_t micro_font[16][10] = {")
    for i, g in enumerate(micro):
        print("    { /* %X */" % i)
        print(fmt_bytes(g))
        print("    },")
    print("};")
    print()
    emit_big(big)
    print()
    print("#endif /* SPIDRIVER_FONTS_H */")

    # sanity output to stderr
    import sys

    for ch, w, h, bits in big:
        print("glyph %r %dx%d (%d bytes)" % (ch, w, h, len(bits)), file=sys.stderr)


if __name__ == "__main__":
    main()
